# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miner',
        ),
    ]
