# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pimon', '0002_delete_miner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('algo', models.CharField(default='any', max_length=100)),
                ('hash', models.FloatField(default='0.0')),
                ('power', models.FloatField(default='0.0')),
                ('price', models.FloatField(default='0.0')),
                ('software', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Myrig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algo', models.CharField(default='any', max_length=100)),
                ('hash', models.FloatField(default='0.0')),
                ('power', models.FloatField(default='0.0')),
                ('price', models.FloatField(default='0.0')),
                ('monitor', models.CharField(default='yes', max_length=3)),
                ('address', models.CharField(default='0.0.0.0', max_length=15)),
                ('software', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('reset', models.CharField(default='no', max_length=3)),
                ('temp', models.FloatField(default='80.0')),
                ('hashr', models.FloatField(default='0.0')),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pimon.Miner')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
