# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0003_miner_myrig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='port',
            field=models.IntegerField(choices=[(1, b'yes'), (2, b'no')], default='yes'),
        ),
    ]
