# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0004_auto_20180830_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='port',
            field=models.IntegerField(choices=[(1, b'yes'), (2, b'no')], default=1),
        ),
        migrations.AlterField(
            model_name='miner',
            name='type',
            field=models.CharField(choices=[(1, b'ASIC'), (2, b'FPGA'), (3, b'Custom FPGA'), (4, b'Custom GPU')], default=1, max_length=100),
        ),
    ]
