# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0006_auto_20180830_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='miner',
            name='type',
            field=models.CharField(choices=[(b'ASIC', b'ASIC'), (b'FPGA', b'FPGA'), (b'cFPGA', b'Custom FPGA'), (b'GPU', b'GPU')], default=b'ASIC', max_length=5),
        ),
    ]
