# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0013_auto_20180830_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrig',
            name='algo',
            field=models.CharField(choices=[(b'ASIC', b'ASIC'), (b'FPGA', b'FPGA'), (b'cFPGA', b'Custom FPGA'), (b'GPU', b'GPU')], default='Any', max_length=10),
        ),
    ]
