# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0016_auto_20180830_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='myrig',
            options={'ordering': ['name']},
        ),
    ]
