# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 05:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0022_auto_20180902_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configglobal',
            name='module',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'PDU/Power', b'PDU/Power'), (b'Forecast', b'Forecast'), (b'Ambient Temps', b'Ambient Temps'), (b'Whattomine Module', b'Whattomine Module'), (b'Profit Monitor', b'Profit Monitor'), (b'Wallet Module', b'Wallet Module'), (b'Pool Monitor', b'Pool Monitor'), (b'ASIC Monitor', b'ASIC Monitor'), (b'GPU Monitor', b'GPU Monitor'), (b'Price Ticker', b'Price Ticker'), (b'iFrame Module', b'iFrame Module')], max_length=144),
        ),
    ]
