# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0023_auto_20180902_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walletcoin', to='pimon.Coin')),
            ],
        ),
    ]
