# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0025_auto_20180902_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='cmc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='wtm',
            field=models.IntegerField(default=0),
        ),
    ]
