# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0028_auto_20180902_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configticker',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pimon.Coin'),
        ),
    ]
