# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0030_auto_20180902_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypool',
            name='autosw',
        ),
        migrations.AlterField(
            model_name='configpool',
            name='autosw',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'no', max_length=3),
        ),
    ]
