# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0031_auto_20180908_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpool',
            name='balanceurl1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='configpool',
            name='balanceurl2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='configpool',
            name='dashboardurl1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='configpool',
            name='dashboardurl2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
