# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0032_auto_20180908_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='configpool',
            name='autoswuse',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'no', max_length=3),
        ),
        migrations.AlterField(
            model_name='configpool',
            name='autosw',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
