# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0033_auto_20180908_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwtm',
            name='customhash',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='configwtm',
            name='custompower',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='configwtm',
            name='customprice',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='configwtm',
            name='onlymyrigs',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'no', max_length=3),
        ),
    ]
