# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0035_auto_20180909_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configwtm',
            name='onlymyrigs',
        ),
        migrations.AddField(
            model_name='configglobal',
            name='wtmincludemyrigs',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'yes', max_length=3),
        ),
    ]
