# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0036_auto_20180913_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='enable',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'no', max_length=3),
        ),
        migrations.AddField(
            model_name='configwallet',
            name='balance',
            field=models.FloatField(default='0.0'),
        ),
    ]
