# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0037_auto_20180913_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configglobal',
            name='electriccost',
            field=models.FloatField(default='10.1'),
        ),
    ]
