# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0039_auto_20180914_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrig',
            name='ttwait',
        ),
        migrations.AddField(
            model_name='configglobal',
            name='asiccheck',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='configglobal',
            name='asicreset',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='configglobal',
            name='gpucheck',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='configglobal',
            name='gpureset',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='myrig',
            name='monitoremail',
            field=models.CharField(choices=[(b'yes', b'yes'), (b'no', b'no')], default=b'yes', max_length=3),
        ),
    ]
