# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0040_auto_20180919_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configglobal',
            name='forecastrefresh',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='pdurefresh',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='poolrefresh',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='profitrefresh',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='temprefresh',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='walletrefresh',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='wtmrefresh',
            field=models.IntegerField(default=30),
        ),
    ]
