# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0042_auto_20180919_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrig',
            name='resettime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myrig',
            name='statustime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
