# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0043_auto_20180919_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='configglobal',
            name='asicresetwait',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='configglobal',
            name='gpuresetwait',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='miner',
            name='type',
            field=models.CharField(choices=[(b'ASIC', b'ASIC'), (b'sFPGA', b'FPGA'), (b'cFPGA', b'cFPGA'), (b'GPU', b'GPU')], max_length=15),
        ),
    ]
