# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0047_auto_20180921_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrig',
            name='firststatus',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myrig',
            name='resetcounter',
            field=models.IntegerField(default=0),
        ),
    ]
