# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0048_auto_20180926_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='configglobal',
            name='asicresetattempts',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='configglobal',
            name='gpuresetattempts',
            field=models.FloatField(default=3),
        ),
    ]
