# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0050_auto_20180927_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configpool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
