# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0051_auto_20180929_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='configglobal',
            name='autosetup',
            field=models.IntegerField(default=0),
        ),
    ]
