# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0053_auto_20181004_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='abv',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configglobal',
            name='electriccost',
            field=models.FloatField(default='10.1'),
        ),
    ]
