# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0054_auto_20181004_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='grav',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='polo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
