# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimon', '0056_auto_20181004_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='cbri',
            field=models.IntegerField(default=0),
        ),
    ]
